#if !canImport(ObjectiveC)
import XCTest

extension GimliTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__GimliTests = [
        ("testGimli", testGimli),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(GimliTests.__allTests__GimliTests),
    ]
}
#endif
